"""empty message

Revision ID: ac3bd0ee038b
Revises: e6156b12d2de
Create Date: 2024-01-16 12:12:59.571951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac3bd0ee038b'
down_revision = 'e6156b12d2de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_lists',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('permissions', sa.Enum('READ', 'WRITE', 'ADMIN', name='permission'), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['to_do_list.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'list_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shared_lists')
    # ### end Alembic commands ###
