"""empty message

Revision ID: e6156b12d2de
Revises: 6c06f9988b40
Create Date: 2024-01-16 11:03:31.967600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6156b12d2de'
down_revision = '6c06f9988b40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('NEW', 'STARTED', 'COMPLETED', name='taskstatus'), nullable=True))
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('completed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('due_date')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
